### ISSUE TITLE
Suggestion : AlbumArt quality

### ISSUE THREAD

**Issue by Kouent** [Wykks/Untamed-Now-Playing-Next#65]
Hi there !
First of all i'd like to thank you guys a lot for that awesome work you've done, it helps me a lot to stream with OBS :)

I had an idea in mind : could we choose the resolution of the AlbumArt which is saved, or at least tick an HD option ? because i like to show it on my stream, but the default resolution is really low, so it isn't really beautiful when displayed. (meanwhile soundcloud provides a picture with a decent resolution)

Best reguards,
Kouent.

**Comment by Wykks** [comment]
Hi !
I don't think an option is needed here, because you can always downgrade the quality, so the idea is to directly get a good/HD quality as much as possible.
And it seems like it hasn't been done correctly for soundcloud :D

I'll improve the soundcloud support in order to get a better album art :)
Thanks for your support !

**Comment by Wykks** [comment]
Done !

**Comment by Kouent** [comment]
Thanks a lot !

**Comment by Kouent** [comment]
Hmmm well, do I need to re-download the plugin ? because the quality is still the same for me right now

**Comment by deltaidea** [comment]
This issue has a "Done (not released yet)" label right now. Relevant changes aren't released to the Mozilla addon store.

You can [compile the addon from source](https://github.com/Wykks/Untamed-Now-Playing-Next#build-latest-dev-version) and install it locally.

**Comment by Wykks** [comment]
Sorry to keep you waiting, release done ! :)
